### PR TITLE
Not really a pull request - fix solver

### PR DESCRIPTION
**Pull request by NPounder**
I saved the changes that @jgomezdans made to the solver in my cloned repository in branch newSolver. Simultaneously he transcribed the changes to his own cloned repository which I believe is what is in fix_solver.

This pull request is to document the differences between those two branches. @jgomezdans can you check all of the changes were correctly transcribed and update fix_solver as necessary?

### CODE REVIEW

**Comment by jgomezdans** [comment]
Hi,
I merged my fixes onto master, as I couldn't quite see what version was what in this PR (yeah, I know). It looks pretty similar to yours (bar the filenames and constants), as far as I can see

**Comment by NPounder** [comment]
Yeah, I was a bit confused by it. Apart from the constants and filenames the differences seemed to be with flattening and ravelling of the mask in solvers and linear_kernals_kf. I'll test out master and see if it works.

**Comment by NPounder** [comment]
I can't see your merge into master. Please could you push it to github.

**Comment by jgomezdans** [comment]
My last merge was 75cf56d0b17cfd3668958d312ac7b131d69ffce8 (which is now HEAD).

**Pull request closed without merging**
